#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <iostream>

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MainFrame
{
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
		~GUIMyFrame1();
	private:
		using size = short unsigned int;

		size _width = wxDefaultSize.GetWidth(); // panel0 width
		size _height = wxDefaultSize.GetHeight(); // panel0 height
		
		wxSize _p0size = wxSize(_width, _height); // panel0 size
		wxSize _pDownSize = wxSize(wxDefaultSize.GetWidth(), wxDefaultSize.GetHeight());

		size lupaX;
		size lupaY;

		wxImage _Image;
		wxBitmap _Bitmap;

		void setPanelsOnLoad(wxString path = _("kotek.jpg"));
		void setPanelSize();
		void Mouse_Move(wxMouseEvent& event);

	public:

		virtual void m_panel1OnPaint(wxPaintEvent& event) override;
		virtual void m_panel0OnUpdateUI(wxUpdateUIEvent& event) override;

		virtual void m_filePicker2OnFileChanged( wxFileDirPickerEvent& event ) override;


};

#endif // __GUIMyFrame1__
