#ifndef __GUIMainFrame__
#define __GUIMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing MainFrame */
class GUIMainFrame : public MainFrame
{
	public:
		/** Constructor */
		GUIMainFrame( wxWindow* parent );
	//// end generated class members

};

#endif // __GUIMainFrame__
